// @author kongweiguang
// SPDX-License-Identifier: GPL-3.0-or-later

//! JA-RPC v1 冻结错误目录；与 framing 分离，避免传输层维护业务错误表。

/// Rust host 可以发起的唯一 JA-RPC v1 request 闭集；握手宣告与 decoder admission
/// 共用此表，避免两个手写清单发生漂移。
pub(crate) const V1_CLIENT_METHODS: &[&str] = &[
    "runtime/initialize",
    "runtime/health",
    "runtime/shutdown",
    "workspace/open",
    "workspace/open-general",
    "workspace/list",
    "workspace/path/search",
    "workspace/set-trust",
    "workspace/unregister",
    "thread/create",
    "thread/list",
    "thread/search",
    "thread/read",
    "thread/rename",
    "thread/pin",
    "thread/seen",
    "thread/preferences/update",
    "thread/archive",
    "thread/restore",
    "thread/delete",
    "thread/compact",
    "interaction/read",
    "interaction/observe",
    "interaction/unobserve",
    "interaction/draft/save",
    "interaction/respond",
    "interaction/cancel",
    "goal/read",
    "goal/events/read",
    "goal/observe",
    "goal/unobserve",
    "plan/read",
    "plan/revisions/list",
    "plan/current/read",
    "plan/events/read",
    "plan/observe",
    "plan/unobserve",
    "plan/evidence/list",
    "goal/evidence/list",
    "goal/create",
    "goal/plan/attach",
    "goal/plan/detach",
    "goal/pause",
    "goal/resume",
    "goal/stop",
    "plan/create",
    "plan/draft/save",
    "plan/draft/discard",
    "plan/propose",
    "plan/execute",
    "plan/reject",
    "plan/pause",
    "plan/resume",
    "plan/stop",
    "task/create",
    "task/list",
    "task/read",
    "task/observe",
    "task/unobserve",
    "task/seen",
    "thread/message/send",
    "task/followup",
    "task/cancel",
    "task/tree/delete",
    "task/close",
    "attachment/import",
    "attachment/discard",
    "attachment/preview/open",
    "attachment/preview/read",
    "attachment/preview/close",
    "turn/start",
    "turn/resume",
    "turn/cancel",
    "turn/input/enqueue",
    "turn/input/prioritize",
    "turn/input/update",
    "turn/input/delete",
    "turn/change-set/read",
    "approval/respond",
    "configuration/read",
    "configuration/patch",
    "configuration/replace",
    "configuration/reset",
    "credential/set",
    "credential/delete",
    "skill/list",
    "mcp/list",
    "mcp/test",
    "model/test",
    "mcp/list-tools",
    "tool/artifact/read",
];

/// App Server 可以推送的唯一 JA-RPC v1 event 闭集；decoder 只接受此表或初始化握手。
pub(crate) const V1_EVENT_METHODS: &[&str] = &[
    "runtime/status-changed",
    "turn/state-changed",
    "turn/input-queue-changed",
    "turn/input-consumed",
    "turn/messages_received",
    "assistant/model-step-committed",
    "assistant/text-delta",
    "assistant/reasoning-summary-delta",
    "tool/started",
    "tool/batch-committed",
    "approval/requested",
    "approval/resolved",
    "context/compaction-started",
    "context/compacted",
    "context/compaction-failed",
    "workspace/dirty",
    "turn/terminal",
    "thread/metadata-changed",
    "configuration/changed",
    "task/activity",
    "task/progress",
    "task/mailbox-changed",
    "goal/changed",
    "goal/activity",
    "interaction/changed",
    "plan/changed",
];

/// 返回唯一 code/errorCode/category/retryable/message 映射，阻止任意诊断文本进入 Wire。
/// 该表逐项对齐机器合同，不保留旧字段、别名或重复机器码。
pub(crate) fn catalog_entry(
    code: i64,
    error_code: &str,
    category: &str,
    retryable: bool,
) -> Option<(&'static str, &'static str)> {
    const CATALOG: &[(i64, &str, &str, bool, &str)] = &[
        (-32_001, "INVALID_FRAME", "protocol", false, "invalid frame"),
        (
            -32_002,
            "FRAME_TOO_LARGE",
            "capacity",
            false,
            "frame too large",
        ),
        (
            -32_003,
            "PROTOCOL_VERSION_UNSUPPORTED",
            "protocol",
            false,
            "protocol version unsupported",
        ),
        (
            -32_004,
            "NOT_INITIALIZED",
            "conflict",
            false,
            "not initialized",
        ),
        (
            -32_005,
            "ALREADY_INITIALIZED",
            "conflict",
            false,
            "already initialized",
        ),
        (
            -32_006,
            "METHOD_NOT_FOUND",
            "not_found",
            false,
            "method not found",
        ),
        (
            -32_007,
            "INVALID_PARAMS",
            "validation",
            false,
            "invalid params",
        ),
        (-32_008, "QUEUE_FULL", "capacity", true, "queue full"),
        (
            -32_009,
            "THREAD_QUEUE_FULL",
            "capacity",
            true,
            "thread queue full",
        ),
        (
            -32_010,
            "CONFIG_INVALID",
            "validation",
            false,
            "config invalid",
        ),
        (
            -32_011,
            "CONFIG_CONFLICT",
            "conflict",
            true,
            "config conflict",
        ),
        (
            -32_012,
            "STORAGE_UNAVAILABLE",
            "unavailable",
            true,
            "storage unavailable",
        ),
        (
            -32_013,
            "CONFIG_CORRUPTED",
            "validation",
            false,
            "config corrupted",
        ),
        (
            -32_014,
            "REQUEST_DEADLINE_EXCEEDED",
            "timeout",
            true,
            "request deadline exceeded",
        ),
        (
            -32_015,
            "CREDENTIAL_MISSING",
            "not_found",
            false,
            "credential missing",
        ),
        (
            -32_016,
            "RECOVERY_REQUIRED",
            "conflict",
            false,
            "recovery required",
        ),
        (
            -32_017,
            "PROVIDER_OR_MODEL_NOT_FOUND",
            "not_found",
            false,
            "provider or model is unavailable",
        ),
        (
            -32_018,
            "WORKSPACE_TRUST_REQUIRED",
            "permission",
            false,
            "workspace trust required",
        ),
        (
            -32_019,
            "STORAGE_CONFLICT",
            "conflict",
            false,
            "storage conflict",
        ),
        (
            -32_020,
            "SHUTTING_DOWN",
            "unavailable",
            true,
            "shutting down",
        ),
        (
            -32_021,
            "DATA_DIR_IN_USE",
            "conflict",
            false,
            "data directory in use",
        ),
        (
            -32_024,
            "SCHEMA_MISMATCH",
            "conflict",
            false,
            "schema mismatch",
        ),
        (
            -32_025,
            "WORKSPACE_NOT_FOUND",
            "not_found",
            false,
            "workspace not found",
        ),
        (
            -32_026,
            "WORKSPACE_CONFINEMENT",
            "permission",
            false,
            "workspace confinement",
        ),
        (-32_028, "CONFLICT", "conflict", true, "conflict"),
        (
            -32_029,
            "THREAD_NOT_FOUND",
            "not_found",
            false,
            "thread not found",
        ),
        (-32_030, "THREAD_BUSY", "conflict", true, "thread busy"),
        (
            -32_032,
            "TURN_NOT_FOUND",
            "not_found",
            false,
            "turn not found",
        ),
        (-32_034, "INVALID_STATE", "conflict", false, "invalid state"),
        (-32_035, "CANCELLED", "cancelled", false, "cancelled"),
        (
            -32_036,
            "BUDGET_EXCEEDED",
            "capacity",
            false,
            "budget exceeded",
        ),
        (
            -32_040,
            "APPROVAL_NOT_FOUND",
            "not_found",
            false,
            "approval not found",
        ),
        (
            -32_041,
            "APPROVAL_EXPIRED",
            "timeout",
            false,
            "approval expired",
        ),
        (
            -32_042,
            "APPROVAL_ALREADY_RESOLVED",
            "conflict",
            false,
            "approval already resolved",
        ),
        (-32_043, "TOOL_DENIED", "permission", false, "tool denied"),
        (-32_044, "TOOL_FAILED", "validation", false, "tool failed"),
        (
            -32_045,
            "TOOL_OUTCOME_UNKNOWN",
            "internal",
            false,
            "tool outcome unknown",
        ),
        (
            -32_046,
            "PROCESS_TIMEOUT",
            "timeout",
            false,
            "process timeout",
        ),
        (
            -32_047,
            "PROCESS_OUTPUT_LIMIT",
            "capacity",
            false,
            "process output limit",
        ),
        (
            -32_049,
            "SUMMARY_FAILURE",
            "unavailable",
            true,
            "summary failure",
        ),
        (
            -32_050,
            "MODEL_PROTOCOL_ERROR",
            "protocol",
            false,
            "model protocol error",
        ),
        (-32_051, "CONTEXT_LIMIT", "capacity", false, "context limit"),
        (
            -32_052,
            "MODEL_UNSUPPORTED",
            "validation",
            false,
            "model unsupported",
        ),
        (
            -32_053,
            "MODEL_UNAVAILABLE",
            "unavailable",
            true,
            "model unavailable",
        ),
        (
            -32_054,
            "SKILL_INVALID",
            "validation",
            false,
            "skill invalid",
        ),
        (
            -32_055,
            "SKILL_UNAVAILABLE",
            "unavailable",
            true,
            "skill unavailable",
        ),
        (
            -32_056,
            "MCP_UNSUPPORTED",
            "validation",
            false,
            "mcp unsupported",
        ),
        (
            -32_057,
            "MCP_SERVER_UNAVAILABLE",
            "unavailable",
            true,
            "mcp server unavailable",
        ),
        (
            -32_059,
            "MCP_TOOL_NOT_FOUND",
            "not_found",
            false,
            "mcp tool not found",
        ),
        (
            -32_060,
            "MCP_TOOL_FAILED",
            "validation",
            false,
            "mcp tool failed",
        ),
        (
            -32_061,
            "ATTACHMENT_NOT_FOUND",
            "not_found",
            false,
            "attachment not found",
        ),
        (
            -32_062,
            "ATTACHMENT_LIMIT_EXCEEDED",
            "capacity",
            false,
            "attachment limit exceeded",
        ),
        (
            -32_063,
            "ATTACHMENT_CONFLICT",
            "conflict",
            false,
            "attachment conflict",
        ),
        (
            -32_064,
            "ATTACHMENT_UNAVAILABLE",
            "unavailable",
            true,
            "attachment unavailable",
        ),
        (
            -32_065,
            "TURN_NOT_RESUMABLE",
            "conflict",
            false,
            "turn is not resumable",
        ),
        (
            -32_066,
            "TURN_RESUME_ORDER_CONFLICT",
            "conflict",
            true,
            "an earlier turn must be resolved first",
        ),
        (
            -32_068,
            "TURN_INPUT_QUEUE_FULL",
            "capacity",
            true,
            "turn input queue is full",
        ),
        (
            -32_069,
            "QUEUED_INPUT_NOT_FOUND",
            "not_found",
            false,
            "queued input was not found",
        ),
        (
            -32_070,
            "WORKSPACE_REFERENCE_INVALID",
            "validation",
            false,
            "workspace reference is invalid",
        ),
        (
            -32_071,
            "SKILL_LOAD_FAILED",
            "unavailable",
            true,
            "skill load failed",
        ),
        (
            -32_072,
            "CONTENT_TOO_LARGE",
            "capacity",
            false,
            "content is too large",
        ),
        (
            -32_073,
            "TASK_NOT_FOUND",
            "not_found",
            false,
            "task not found",
        ),
        (
            -32_074,
            "TASK_RELATION_INVALID",
            "validation",
            false,
            "task relation is invalid",
        ),
        (
            -32_075,
            "TASK_CONTEXT_REVISION_CONFLICT",
            "conflict",
            true,
            "task context revision conflicts",
        ),
        (
            -32_076,
            "TASK_PERMISSION_DENIED",
            "permission",
            false,
            "task permission denied",
        ),
        (
            -32_077,
            "TASK_DEPTH_LIMIT",
            "capacity",
            false,
            "task depth limit reached",
        ),
        (
            -32_078,
            "TASK_TREE_LIMIT",
            "capacity",
            false,
            "task tree limit reached",
        ),
        (
            -32_079,
            "TASK_MAILBOX_FULL",
            "capacity",
            true,
            "task mailbox is full",
        ),
        (
            -32_080,
            "INTERNAL_ERROR",
            "internal",
            false,
            "internal error",
        ),
        (
            -32_081,
            "SIDECAR_CRASHED",
            "unavailable",
            false,
            "sidecar crashed",
        ),
        (
            -32_082,
            "SHUTDOWN_TIMEOUT",
            "timeout",
            false,
            "shutdown timeout",
        ),
        (
            -32_083,
            "TASK_TREE_DELETE_REQUIRED",
            "conflict",
            false,
            "task tree deletion is required",
        ),
        (
            -32_084,
            "TASK_OBSERVATION_INVALID",
            "not_found",
            false,
            "task observation is invalid",
        ),
        (
            -32_085,
            "WORKSPACE_WRITE_LEASE_TIMEOUT",
            "timeout",
            true,
            "workspace write lease timed out",
        ),
        (
            -32_086,
            "GOAL_NOT_FOUND",
            "not_found",
            false,
            "goal not found",
        ),
        (
            -32_087,
            "GOAL_REVISION_CONFLICT",
            "conflict",
            true,
            "goal revision conflicts",
        ),
        (
            -32_088,
            "GOAL_INVALID_STATE",
            "conflict",
            false,
            "goal state is invalid",
        ),
        (
            -32_089,
            "PLAN_INVALID",
            "validation",
            false,
            "plan is invalid",
        ),
        (
            -32_090,
            "PLAN_APPROVAL_STALE",
            "conflict",
            false,
            "plan approval is stale",
        ),
        (
            -32_091,
            "GOAL_EVIDENCE_INCOMPLETE",
            "conflict",
            false,
            "goal evidence is incomplete",
        ),
        (
            -32_092,
            "GOAL_RECOVERY_REQUIRED",
            "conflict",
            false,
            "goal recovery is required",
        ),
        (
            -32_094,
            "INTERACTION_NOT_FOUND",
            "not_found",
            false,
            "interaction was not found",
        ),
        (
            -32_095,
            "INTERACTION_REVISION_CONFLICT",
            "conflict",
            true,
            "interaction revision changed",
        ),
        (
            -32_096,
            "INTERACTION_INVALID_STATE",
            "conflict",
            false,
            "interaction state does not allow this operation",
        ),
        (
            -32_097,
            "INTERACTION_INVALID",
            "validation",
            false,
            "interaction is invalid",
        ),
        (
            -32_098,
            "PLAN_REVISION_CONFLICT",
            "conflict",
            true,
            "plan revision changed",
        ),
        (
            -32_099,
            "PLAN_INVALID_STATE",
            "conflict",
            false,
            "plan state does not allow this operation",
        ),
    ];
    CATALOG
        .iter()
        .find(
            |(entry_code, entry_error, entry_category, entry_retryable, _)| {
                *entry_code == code
                    && *entry_error == error_code
                    && *entry_category == category
                    && *entry_retryable == retryable
            },
        )
        .map(|(_, entry_error, _, _, message)| (*entry_error, *message))
}
