// @author kongweiguang
// SPDX-License-Identifier: GPL-3.0-or-later

//! JA-RPC v2 冻结错误目录；与 framing 分离，避免传输层维护业务错误表。

/// Rust host 可以发起的唯一 JA-RPC v2 request 闭集；握手宣告与 decoder admission
/// 共用此表，避免两个手写清单发生漂移。
pub(crate) const V2_CLIENT_METHODS: &[&str] = &[
    "runtime/initialize",
    "runtime/health",
    "runtime/shutdown",
    "workspace/open",
    "workspace/open-general",
    "workspace/list",
    "workspace/set-trust",
    "workspace/unregister",
    "thread/create",
    "thread/list",
    "thread/search",
    "thread/read",
    "thread/rename",
    "thread/preferences/update",
    "thread/archive",
    "thread/delete",
    "thread/compact",
    "attachment/import",
    "attachment/discard",
    "turn/start",
    "turn/cancel",
    "turn/steer",
    "turn/follow-up",
    "turn/change-set/commit",
    "turn/change-set/read",
    "approval/respond",
    "configuration/read",
    "configuration/patch",
    "configuration/replace",
    "configuration/reset",
    "credential/set",
    "credential/delete",
    "skill/list",
    "mcp/list",
    "mcp/test",
    "model/test",
    "mcp/list-tools",
    "tool/artifact/read",
];

/// App Server 可以推送的唯一 JA-RPC v2 event 闭集；decoder 只接受此表或初始化握手。
pub(crate) const V2_EVENT_METHODS: &[&str] = &[
    "runtime/status-changed",
    "turn/state-changed",
    "assistant/model-step-committed",
    "assistant/text-delta",
    "assistant/reasoning-summary-delta",
    "tool/batch-committed",
    "approval/requested",
    "approval/resolved",
    "context/compaction-started",
    "context/compacted",
    "context/compaction-failed",
    "workspace/dirty",
    "turn/terminal",
    "thread/metadata-changed",
    "configuration/changed",
];

/// 返回唯一 code/errorCode/category/retryable/message 映射，阻止任意诊断文本进入 Wire。
/// 该表逐项对齐机器合同，不保留旧字段、别名或重复机器码。
pub(crate) fn catalog_entry(
    code: i64,
    error_code: &str,
    category: &str,
    retryable: bool,
) -> Option<(&'static str, &'static str)> {
    const CATALOG: &[(i64, &str, &str, bool, &str)] = &[
        (-32_001, "INVALID_FRAME", "protocol", false, "invalid frame"),
        (
            -32_002,
            "FRAME_TOO_LARGE",
            "capacity",
            false,
            "frame too large",
        ),
        (
            -32_003,
            "PROTOCOL_VERSION_UNSUPPORTED",
            "protocol",
            false,
            "protocol version unsupported",
        ),
        (
            -32_004,
            "NOT_INITIALIZED",
            "conflict",
            false,
            "not initialized",
        ),
        (
            -32_005,
            "ALREADY_INITIALIZED",
            "conflict",
            false,
            "already initialized",
        ),
        (
            -32_006,
            "METHOD_NOT_FOUND",
            "not_found",
            false,
            "method not found",
        ),
        (
            -32_007,
            "INVALID_PARAMS",
            "validation",
            false,
            "invalid params",
        ),
        (-32_008, "QUEUE_FULL", "capacity", true, "queue full"),
        (
            -32_009,
            "THREAD_QUEUE_FULL",
            "capacity",
            true,
            "thread queue full",
        ),
        (
            -32_010,
            "CONFIG_INVALID",
            "validation",
            false,
            "config invalid",
        ),
        (
            -32_011,
            "CONFIG_CONFLICT",
            "conflict",
            true,
            "config conflict",
        ),
        (
            -32_012,
            "STORAGE_UNAVAILABLE",
            "unavailable",
            true,
            "storage unavailable",
        ),
        (
            -32_013,
            "CONFIG_CORRUPTED",
            "validation",
            false,
            "config corrupted",
        ),
        (
            -32_014,
            "REQUEST_DEADLINE_EXCEEDED",
            "timeout",
            true,
            "request deadline exceeded",
        ),
        (
            -32_015,
            "CREDENTIAL_MISSING",
            "not_found",
            false,
            "credential missing",
        ),
        (
            -32_016,
            "RECOVERY_REQUIRED",
            "conflict",
            false,
            "recovery required",
        ),
        (
            -32_017,
            "PROVIDER_OR_MODEL_NOT_FOUND",
            "not_found",
            false,
            "provider or model is unavailable",
        ),
        (
            -32_018,
            "WORKSPACE_TRUST_REQUIRED",
            "permission",
            false,
            "workspace trust required",
        ),
        (
            -32_019,
            "STORAGE_CONFLICT",
            "conflict",
            false,
            "storage conflict",
        ),
        (
            -32_020,
            "SHUTTING_DOWN",
            "unavailable",
            true,
            "shutting down",
        ),
        (
            -32_021,
            "DATA_DIR_IN_USE",
            "conflict",
            false,
            "data directory in use",
        ),
        (
            -32_024,
            "SCHEMA_MISMATCH",
            "conflict",
            false,
            "schema mismatch",
        ),
        (
            -32_025,
            "WORKSPACE_NOT_FOUND",
            "not_found",
            false,
            "workspace not found",
        ),
        (
            -32_026,
            "WORKSPACE_CONFINEMENT",
            "permission",
            false,
            "workspace confinement",
        ),
        (-32_028, "CONFLICT", "conflict", true, "conflict"),
        (
            -32_029,
            "THREAD_NOT_FOUND",
            "not_found",
            false,
            "thread not found",
        ),
        (-32_030, "THREAD_BUSY", "conflict", true, "thread busy"),
        (
            -32_032,
            "TURN_NOT_FOUND",
            "not_found",
            false,
            "turn not found",
        ),
        (-32_034, "INVALID_STATE", "conflict", false, "invalid state"),
        (-32_035, "CANCELLED", "cancelled", false, "cancelled"),
        (
            -32_036,
            "BUDGET_EXCEEDED",
            "capacity",
            false,
            "budget exceeded",
        ),
        (
            -32_040,
            "APPROVAL_NOT_FOUND",
            "not_found",
            false,
            "approval not found",
        ),
        (
            -32_041,
            "APPROVAL_EXPIRED",
            "timeout",
            false,
            "approval expired",
        ),
        (
            -32_042,
            "APPROVAL_ALREADY_RESOLVED",
            "conflict",
            false,
            "approval already resolved",
        ),
        (-32_043, "TOOL_DENIED", "permission", false, "tool denied"),
        (-32_044, "TOOL_FAILED", "validation", false, "tool failed"),
        (
            -32_045,
            "TOOL_OUTCOME_UNKNOWN",
            "internal",
            false,
            "tool outcome unknown",
        ),
        (
            -32_046,
            "PROCESS_TIMEOUT",
            "timeout",
            false,
            "process timeout",
        ),
        (
            -32_047,
            "PROCESS_OUTPUT_LIMIT",
            "capacity",
            false,
            "process output limit",
        ),
        (
            -32_048,
            "TOKEN_COUNT_UNAVAILABLE",
            "unavailable",
            true,
            "token count unavailable",
        ),
        (
            -32_049,
            "SUMMARY_FAILURE",
            "unavailable",
            true,
            "summary failure",
        ),
        (
            -32_050,
            "MODEL_PROTOCOL_ERROR",
            "protocol",
            false,
            "model protocol error",
        ),
        (-32_051, "CONTEXT_LIMIT", "capacity", false, "context limit"),
        (
            -32_052,
            "MODEL_UNSUPPORTED",
            "validation",
            false,
            "model unsupported",
        ),
        (
            -32_053,
            "MODEL_UNAVAILABLE",
            "unavailable",
            true,
            "model unavailable",
        ),
        (
            -32_054,
            "SKILL_INVALID",
            "validation",
            false,
            "skill invalid",
        ),
        (
            -32_055,
            "SKILL_UNAVAILABLE",
            "unavailable",
            true,
            "skill unavailable",
        ),
        (
            -32_056,
            "MCP_UNSUPPORTED",
            "validation",
            false,
            "mcp unsupported",
        ),
        (
            -32_057,
            "MCP_SERVER_UNAVAILABLE",
            "unavailable",
            true,
            "mcp server unavailable",
        ),
        (
            -32_059,
            "MCP_TOOL_NOT_FOUND",
            "not_found",
            false,
            "mcp tool not found",
        ),
        (
            -32_060,
            "MCP_TOOL_FAILED",
            "validation",
            false,
            "mcp tool failed",
        ),
        (
            -32_061,
            "ATTACHMENT_NOT_FOUND",
            "not_found",
            false,
            "attachment not found",
        ),
        (
            -32_062,
            "ATTACHMENT_LIMIT_EXCEEDED",
            "capacity",
            false,
            "attachment limit exceeded",
        ),
        (
            -32_063,
            "ATTACHMENT_CONFLICT",
            "conflict",
            false,
            "attachment conflict",
        ),
        (
            -32_064,
            "ATTACHMENT_UNAVAILABLE",
            "unavailable",
            true,
            "attachment unavailable",
        ),
        (
            -32_080,
            "INTERNAL_ERROR",
            "internal",
            false,
            "internal error",
        ),
        (
            -32_081,
            "SIDECAR_CRASHED",
            "unavailable",
            false,
            "sidecar crashed",
        ),
        (
            -32_082,
            "SHUTDOWN_TIMEOUT",
            "timeout",
            false,
            "shutdown timeout",
        ),
    ];
    CATALOG
        .iter()
        .find(
            |(entry_code, entry_error, entry_category, entry_retryable, _)| {
                *entry_code == code
                    && *entry_error == error_code
                    && *entry_category == category
                    && *entry_retryable == retryable
            },
        )
        .map(|(_, entry_error, _, _, message)| (*entry_error, *message))
}
